export const ADD_COMMENTS = 'ADD_COMMENT';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const PROMOTIONS_LOADING = 'CAMPSITES_LOADING';
export const PROMOTIONS_FAILED = 'CAMPSITES_FAILED';
export const ADD_PROMOTIONS = 'ADD_CAMPSITES';